FROM python:3.11-slim AS build

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY pyproject.toml uv.lock README.md ./

RUN apt update && \
    apt install -y build-essential && \
    apt install -y --no-install-recommends \
    libglib2.0-0 libgl1 libsm6 libxext6 libxrender1 &&\
    rm -rf /var/lib/apt/lists/*

RUN uv sync --no-dev

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt update && \
    apt install -y --no-install-recommends \
    libglib2.0-0 libgl1 libsm6 libxext6 libxrender1 &&\
    rm -rf /var/lib/apt/lists/*

COPY --from=build /app/.venv /app/.venv
COPY --from=build /bin/uv /bin/uv
COPY --from=build /bin/uvx /bin/uvx

# PATH에 uv와 가상환경 추가
ENV PATH="/app/.venv/bin:/bin:$PATH"
ENV PYTHONPATH="/app"

COPY pyproject.toml README.md ./
COPY mcp_satellite_server /app/mcp_satellite_server

EXPOSE 8100

CMD ["uv", "run", "mcp_satellite_server/server.py"]
